[pytest]
markers =
    smoke: mark a test as a smoke test
    home: mark a test as a home screen test
    order: mark the execution order of a test case
    results: mark a test as a results screen test
    regression1: regression1

